[package]
name = "afos"
description = "AFOS is a Fake OS made in Rust"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["socks"] }
tokio = { version = "1", features = ["full"] }