[package]
name = "afos"
description = "AFOS is a Fake OS made in Rust"
version = "1.0.0"
edition = "2021"

[dependencies]
mlua = { version = "0.10.5", features = ["lua54", "vendored"] }
reqwest = { version = "0.12.20", features = ["socks"] }
tokio = { version = "1.45.1", features = ["full"] }
